# Generated by Django 6.0.1 on 2026-02-08 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.DeleteModel(
            name='ProductVideo',
        ),
    ]
