# Generated by Django 6.0.1 on 2026-02-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_video_alter_productimage_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='video',
        ),
    ]
